module.exports = {
    my_hostname: 'localhost',
	database: 'sensecity_dev',
    port: 3000,
	login:'kostas.bakoulias@gmail.com',
	pwd:'demo@1234',
    bugUrl: 'http://localhost/bugzilla/jsonrpc.cgi',
    bugUrlRest: 'http://localhost/bugzilla',
	bug_product: 'testcity1',
	bug_component: 'default',
    bug_cc: '',
    key_geocoding: 'AIzaSyCHBdH6Zw1z3H6NOmAaTIG2TwIPTXUhnvM',
    email: 'sense.city.uop@gmail.com',
    password_email: 'dd3Gt56Asz',
    log_path: "sensecity-log/",
    img_path: "C:/University Git/sensecity-api-dev-imgs/",
    http_port: 3000,
    https_port: 4000,
    minio_accessKey: 'C7BD1NN87R3U2IU6J4ZR',
    minio_secretKey: 'm6hl3wF94Yr38+eY4iaI/COkmRYuq2BOA26DrK/d',
    minio_endPoint: '150.140.184.233',
    minio_port: 8999,
    minio_bucket: 'devbucket',
    minio_temp_folder: 'C:/University Git/delete',
    bugzilla_default_email: 'kostas.bakoulias@gmail.com',
    watson_api_key: 'sXhdMothuCWCYif7uerkVSRovvw88EUJhPaVALuAltCy',
    watsonVersion:'2018-03-19'
}