module.exports = {
    my_hostname: '',
	database: '',
    port: 1234,
	login:'login-name',
	pwd:'password',
	bugUrl:'',
	bug_product: '',
	bug_component: '',
    bug_cc: '',
    key_geocoding: '',
    email: '',
    password_email: '',
    log_path: '',
    img_path: '',
    http_port: 3000,
    https_port: 4000,
    minio_accessKey: '',
    minio_secretKey: '',
    minio_endPoint: '',
    minio_port: 9000,
    minio_bucket: '',
    minio_temp_folder: '',
    bugzilla_default_email: ''
}